package Views;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class IniciarSesión extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesión
     */
    public IniciarSesión() {
        initComponents();
        JBAcceder.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                General general = new General();
                general.setLocationRelativeTo(null);
                general.setVisible(true);
            }
        });
        
        jBSalir.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTUUID = new javax.swing.JTextField();
        jTPIN = new javax.swing.JTextField();
        JCEmpleado = new javax.swing.JCheckBox();
        JCJefe1 = new javax.swing.JCheckBox();
        JBAcceder = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1025, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTUUID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 302, 310, 30));
        jPanel1.add(jTPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 362, 310, 30));

        JCEmpleado.setForeground(new java.awt.Color(102, 102, 102));
        JCEmpleado.setText("Soy empleado");
        JCEmpleado.setBorder(null);
        JCEmpleado.setContentAreaFilled(false);
        JCEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(JCEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        JCJefe1.setForeground(new java.awt.Color(102, 102, 102));
        JCJefe1.setText("Soy jefe");
        JCJefe1.setBorder(null);
        JCJefe1.setContentAreaFilled(false);
        JCJefe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCJefe1ActionPerformed(evt);
            }
        });
        jPanel1.add(JCJefe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        JBAcceder.setBackground(new java.awt.Color(173, 173, 173));
        JBAcceder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBAcceder.setForeground(new java.awt.Color(255, 255, 255));
        JBAcceder.setText("Acceder");
        JBAcceder.setBorder(null);
        JBAcceder.setBorderPainted(false);
        jPanel1.add(JBAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 310, 30));

        jBSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\karen\\OneDrive\\Documentos\\Document\\CICLO VI\\Sistemas de Información II\\Producto\\Phosto_Clasificación\\Group 10087.png")); // NOI18N
        jBSalir.setBorder(null);
        jBSalir.setBorderPainted(false);
        jBSalir.setContentAreaFilled(false);
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\karen\\OneDrive\\Documentos\\Document\\CICLO VI\\Sistemas de Información II\\Producto\\Phosto_Clasificación\\IniciarSesión.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCEmpleadoActionPerformed

    private void JCJefe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCJefe1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCJefe1ActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSalirActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(IniciarSesión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(IniciarSesión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(IniciarSesión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(IniciarSesión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new IniciarSesión().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBAcceder;
    public javax.swing.JCheckBox JCEmpleado;
    public javax.swing.JCheckBox JCJefe1;
    public javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTPIN;
    public javax.swing.JTextField jTUUID;
    // End of variables declaration//GEN-END:variables
}
