package Views;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesión
     */
    public Productos() {
        initComponents();
        
        jBProductos.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){
                    dispose();
                    Productos pro = new Productos();
                    pro.setLocationRelativeTo(null);
                    pro.setVisible(true);
            }
        });

        jBClasificaciónABC.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){
                    dispose();
                    ClasificacionABC clasi = new ClasificacionABC();
                    clasi.setLocationRelativeTo(null);
                    clasi.setVisible(true);
            }
        });

        jBVentas.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){
                dispose();
                Ventas ven = new Ventas();
                ven.setLocationRelativeTo(null);
                ven.setVisible(true);

            }
        });

        jBGenerarInfo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){
                    dispose();
                    GenerarInformes genI = new GenerarInformes();
                    genI.setLocationRelativeTo(null);
                    genI.setVisible(true);
            }
        });
        
        jBSalir.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){
                    dispose();
                    IniciarSesión login = new IniciarSesión();
                    login.setLocationRelativeTo(null);
                    login.setVisible(true);
            }
        });  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBSalir = new javax.swing.JButton();
        jBProductos = new javax.swing.JButton();
        jBClasificaciónABC = new javax.swing.JButton();
        jBVentas = new javax.swing.JButton();
        jBGenerarInfo = new javax.swing.JButton();
        jTDescripP = new javax.swing.JTextField();
        jTCodigoP = new javax.swing.JTextField();
        jTStockP = new javax.swing.JTextField();
        jTPrecioP = new javax.swing.JTextField();
        JCOpcionesClas = new javax.swing.JComboBox<>();
        JBLimpiar = new javax.swing.JButton();
        JBListar1 = new javax.swing.JButton();
        JBEliminar = new javax.swing.JButton();
        JBAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProducto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1025, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\karen\\OneDrive\\Documentos\\Document\\CICLO VI\\Sistemas de Información II\\Producto\\Phosto_Clasificación\\Group 10087.png")); // NOI18N
        jBSalir.setBorder(null);
        jBSalir.setBorderPainted(false);
        jBSalir.setContentAreaFilled(false);
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, -1, -1));

        jBProductos.setIcon(new javax.swing.ImageIcon("C:\\Users\\karen\\OneDrive\\Documentos\\Document\\CICLO VI\\Sistemas de Información II\\Producto\\Phosto_Clasificación\\Group 10119.png")); // NOI18N
        jBProductos.setBorder(null);
        jBProductos.setBorderPainted(false);
        jBProductos.setContentAreaFilled(false);
        jPanel1.add(jBProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jBClasificaciónABC.setIcon(new javax.swing.ImageIcon("C:\\Users\\karen\\OneDrive\\Documentos\\Document\\CICLO VI\\Sistemas de Información II\\Producto\\Phosto_Clasificación\\Group 10120.png")); // NOI18N
        jBClasificaciónABC.setBorder(null);
        jBClasificaciónABC.setBorderPainted(false);
        jBClasificaciónABC.setContentAreaFilled(false);
        jPanel1.add(jBClasificaciónABC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jBVentas.setIcon(new javax.swing.ImageIcon("C:\\Users\\karen\\OneDrive\\Documentos\\Document\\CICLO VI\\Sistemas de Información II\\Producto\\Phosto_Clasificación\\Group 10093.png")); // NOI18N
        jBVentas.setBorder(null);
        jBVentas.setBorderPainted(false);
        jBVentas.setContentAreaFilled(false);
        jPanel1.add(jBVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jBGenerarInfo.setIcon(new javax.swing.ImageIcon("C:\\Users\\karen\\OneDrive\\Documentos\\Document\\CICLO VI\\Sistemas de Información II\\Producto\\Phosto_Clasificación\\Group 10121.png")); // NOI18N
        jBGenerarInfo.setBorder(null);
        jBGenerarInfo.setBorderPainted(false);
        jBGenerarInfo.setContentAreaFilled(false);
        jPanel1.add(jBGenerarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));
        jPanel1.add(jTDescripP, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 310, 30));
        jPanel1.add(jTCodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 310, 30));
        jPanel1.add(jTStockP, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 310, 30));
        jPanel1.add(jTPrecioP, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 310, 30));

        JCOpcionesClas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cristaleria", "Jugueteria", "Comida", "Loceria", "Bebida" }));
        JCOpcionesClas.setBorder(null);
        jPanel1.add(JCOpcionesClas, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 310, 30));

        JBLimpiar.setBackground(new java.awt.Color(173, 173, 173));
        JBLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        JBLimpiar.setText("Limpiar");
        JBLimpiar.setBorder(null);
        JBLimpiar.setBorderPainted(false);
        JBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(JBLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 140, 30));

        JBListar1.setBackground(new java.awt.Color(173, 173, 173));
        JBListar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBListar1.setForeground(new java.awt.Color(255, 255, 255));
        JBListar1.setText("Listar");
        JBListar1.setBorder(null);
        JBListar1.setBorderPainted(false);
        JBListar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBListar1ActionPerformed(evt);
            }
        });
        jPanel1.add(JBListar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 140, 30));

        JBEliminar.setBackground(new java.awt.Color(173, 173, 173));
        JBEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBEliminar.setForeground(new java.awt.Color(255, 255, 255));
        JBEliminar.setText("Eliminar");
        JBEliminar.setBorder(null);
        JBEliminar.setBorderPainted(false);
        JBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(JBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 140, 30));

        JBAgregar.setBackground(new java.awt.Color(173, 173, 173));
        JBAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBAgregar.setForeground(new java.awt.Color(255, 255, 255));
        JBAgregar.setText("Agregar");
        JBAgregar.setBorder(null);
        JBAgregar.setBorderPainted(false);
        JBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(JBAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 140, 30));

        tableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Stock", "Precio", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProducto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 337, 670, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\karen\\OneDrive\\Documentos\\Document\\CICLO VI\\Sistemas de Información II\\Producto\\Phosto_Clasificación\\Productos.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSalirActionPerformed

    private void JBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBLimpiarActionPerformed

    private void JBListar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBListar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBListar1ActionPerformed

    private void JBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBEliminarActionPerformed

    private void JBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBAgregarActionPerformed

    private void tableProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductoMouseClicked

    }//GEN-LAST:event_tableProductoMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Productos().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBAgregar;
    public javax.swing.JButton JBEliminar;
    public javax.swing.JButton JBLimpiar;
    public javax.swing.JButton JBListar1;
    private javax.swing.JComboBox<String> JCOpcionesClas;
    private javax.swing.JButton jBClasificaciónABC;
    private javax.swing.JButton jBGenerarInfo;
    private javax.swing.JButton jBProductos;
    public javax.swing.JButton jBSalir;
    private javax.swing.JButton jBVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jTCodigoP;
    public javax.swing.JTextField jTDescripP;
    public javax.swing.JTextField jTPrecioP;
    public javax.swing.JTextField jTStockP;
    public javax.swing.JTable tableProducto;
    // End of variables declaration//GEN-END:variables
}
